# Generated by Django 2.1.1 on 2018-12-31 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearnerAdress',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
