# Generated by Django 2.1.1 on 2019-01-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190105_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
