# Generated by Django 2.1.1 on 2018-12-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_instructorqualification_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorqualification',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
    ]
