# Generated by Django 2.1.1 on 2019-01-06 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leasson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='now',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
