# Generated by Django 2.1.1 on 2019-01-06 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leasson', '0002_lesson_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='datenow',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
